cat/urls.py
from cat.views import *
from django.urls import path

app_name= 'Caat'

urlpatterns = [
    path('Caat/', Caat , name='Caat'),
    path('kitten/',kitten,name='kitten'),
]

project3/urls.py
from django.contrib import admin
from django.urls import path , include
from dog.views import *
import cat

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dogs/', dogs, name='dogs'),
    path('Dog/',Dog,name='Dog'),
    path('cat/',include('cat.urls')),
    
]

cat/models.py
from django.db import models

# Create your models here.

dog/models.py
from django.db import models

# Create your models here.

cat/views.py
from django.shortcuts import render

# Create your views here.
def Caat(request):
    return render(request, 'Caat.html')

def kitten(request):
    return render(request, 'kitten.html')

dog/views.py
from django.shortcuts import render

# Create your views here.
def dogs(request):
    return render(request, 'dogs.html')

def Dog(request):
    return render(request, 'Dog.html')

templates/Caat.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <center> 
        <h1> Domestic Cat Stock 
        </h1>
        <img src="https://media.istockphoto.com/id/1443562748/photo/cute-ginger-cat.jpg?s=612x612&w=0&k=20&c=vvM97wWz-hMj7DLzfpYRmY2VswTqcFEKkC437hxm3Cg=" alt="">
       <h1> <a href= "{% url 'Caat:kitten'%}">click here for kitten </a> </h1>
       <h1> <a href= '{% url "Dog"%}'>click here for bitbull </a> </h1> 
       <h1> <a href= '{% url "dogs"%}'>click here for Dangerous </a> </h1>
      </center>
    </body>
</html>

templates/Dog.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <center> 
        <h1> the 195 breeds recognized by the AKC
        </h1>
        <img src="https://www.blackburnromey.com/wp-content/uploads/2024/11/American-Pit-Bull-Terrier.jpg" alt="">
        <!-- <h1> <a href= '{% url "Dog"%}'>click here for bitbull </a> </h1> -->
       <h1> <a href= '{% url "dogs"%}'>click here for Dangerous </a> </h1>
       <h1> <a href= "{% url 'Caat:kitten'%}">click here for kitten  </a> </h1>
       <h1> <a href= "{% url 'Caat:Caat'%}">click here for cat </a> </h1>
      </center>
    </body>
</html>

templates/dogs.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <center> 
        <h1> Dangerous Dog Breeds  </h1>
        <img src="https://www.blackburnromey.com/wp-content/uploads/2024/11/Doberman-Pinscher.jpg" alt="">
       <h1> <a href= '{% url "Dog"%}'>click here for pitbull </a> </h1>
       <h1> <a href= "{% url 'Caat:kitten'%}">click here for kitten  </a> </h1>
       <h1> <a href= "{% url 'Caat:Caat'%}">click here for cat </a> </h1>
      </center>
    </body>
</html>

templates/kitten.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      <center> 
        <h1> A Complete Guide To Kitten Care 
        </h1>
        <img src="https://i.pinimg.com/736x/87/07/e2/8707e20fee9bea47c4ecb95bb497a132.jpg" alt="">
       <h1> <a href= "{% url 'Caat:Caat'%}">click here for cat</a> </h1>
        <h1> <a href= '{% url "Dog"%}'>click here for bitbull </a> </h1>
       <h1> <a href= '{% url "dogs"%}'>click here for Dangerous </a> </h1>
      </center>
    </body>
</html>